version: 2.1

orbs:
  maven-spotbugs: cbonoz/maven-spotbugs@0.0.2

jobs:
  maven_test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Install Libs
          command: mvn install -DskipTests=true --settings 'pom.xml'
      - run:
          name: Run Tests
          command: mvn verify --settings 'pom.xml'
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: target/surefire-reports

  sonar_build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

workflows:
  maven_test:
    jobs:
      - maven_test

  spotbugs:
    jobs:
      - maven-spotbugs/run

  sonar:
    jobs:
      - sonar_build:
          context: SonarCloud

  version: 2